manifest = "00352f31890a03f49487a0cd27c3144ca31749132404b8d5ec8ab64f5b5c89f8"

[[dependency]]
package = "github.com/buckaroo-pm/host-core-foundation"
target = "//:core-foundation"

[[dependency]]
package = "github.com/buckaroo-pm/taocpp-pegtl"
target = "//:pegtl"

[lock."github.com/buckaroo-pm/host-core-foundation"]
versions = [ "branch=master" ]
revision = "fd7081ffe1244afb86c41c2d41d3603f851feae8"

[lock."github.com/buckaroo-pm/taocpp-pegtl"]
versions = [ "2.7.1" ]
revision = "539160b1344b901187f282a52a90ce1b69d84e0f"
